version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Logging in to AWS CodeArtifact...
      # UPDATED: Correct Region (ap-south-1), Domain (rayyan), and Account ID
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain rayyan --domain-owner 977099020493 --region ap-south-1 --query authorizationToken --output text`
  build:
    commands:
      - echo Build started on `date`
     
      - mvn clean package -s settings.xml
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/*.war
  # UPDATED: Flattens the folder structure
  discard-paths: yes